apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service-deployment
  labels:
    app: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: logger-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MIRRORD_FAKE_VAR_FIRST
              value: mirrord.is.running
            - name: MIRRORD_FAKE_VAR_SECOND
              value: "7777"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logger-service
  name: logger-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080      
  selector:
    app: logger-service
  sessionAffinity: None
  type: NodePort